-- We analyze the expressivess of our new foundation here
import DBSP.Termination.Spec
import DBSP.Termination.FPProp
import DBSP.Circuits.LiftedScalar
open CktBasic

-- We first prove some lemmas for LiftedScalar circuits
section Ext2Int
variable {ns: Bool} {A B C: VType}

lemma FixedAfter1_LiftedScalar
  (c: Ckt A B ns) (hc: LiftedScalar c)
  x n (hfa: FixedAfter1 x n):
    FixedAfter1 (denote c x) n := by
  apply LiftedScalar_Denote at hc
  rcases hc with ⟨f, hf⟩
  rw [hf]; apply FixedAfter1_liftO; tauto

lemma ExtFP1_LiftedScalar_IntFP1
  (c: Ckt A B ns) (hc: LiftedScalar c)
  x n (he: ExtFP1 c x n):
    IntFP1 c x n := by
  induction hc
  case seq c1 c2 h1 h2 ih1 ih2 =>
    simp [IntFP1]
    have : ExtFP1 c1 x n := by
      simp [ExtFP1] at he ⊢
      constructor; tauto
      apply LiftedScalar_Denote at h1
      rcases h1 with ⟨f, hf⟩
      rw [hf]; apply FixedAfter1_liftO; tauto
    have : ExtFP1 c2 (denote c1 x) n := by
      constructor; swap
      · apply he.2
      apply FixedAfter1_LiftedScalar; assumption
      apply this.1
    constructor
    · apply ih1; assumption
    · apply ih2; assumption
  case par c1 c2 h1 h2 ih1 ih2 =>
    simp [IntFP1]
    simp [ExtFP1, denote] at he
    rw [FixedAfter1_sprodO] at he
    constructor
    · apply ih1; simp [ExtFP1]; tauto
    · apply ih2; simp [ExtFP1]; tauto
  all_goals
    try (simp [IntFP1]; assumption)

@[simp]
theorem Terminate_LiftedScalar
  (c: Ckt A B ns) (hc: LiftedScalar c) x:
    Terminate c x := by
  induction hc <;> try constructor <;> try tauto
  simp [Terminate]; tauto

end Ext2Int

section Expressiveness

-- Some lemmas on function iteration.

-- The stream generated by function iteration of `f` on `x`
-- i.e. `x, f(x), f(f(x)), f(f(f(x))), ...`
def funcIterStream {A: Type} (f: A -> A) (x: A): stream A :=
  fun n => f^[n] x

def FixedAt {A: Type} (f: A -> A) (x: A) (n: ℕ): Prop :=
    f^[n+1] x = f^[n] x

def FixedAtVec {A: Type} (f: A -> A) (x: stream A) (b: stream ℕ): Prop :=
  ∀ i, FixedAt f (x i) (b i)

lemma FixedAt_funcIterStream_iff {A: Type} (f: A -> A) (x: A) (n: ℕ):
    FixedAt f x n <-> FixedAfter1 (funcIterStream f x) n := by
  unfold FixedAt
  constructor
  · intro h; rw [add_comm] at h
    rw [Function.iterate_add_apply] at h; simp at h
    intro m hm; simp [funcIterStream]
    apply Function.iterate_fixed at h
    specialize h (m-n)
    rw [<- Function.iterate_add_apply] at h
    rw [<- h]; congr; omega
  · intro h
    apply h; omega

lemma FixedAt_mono {A: Type} (f: A -> A) (x: A) (n: ℕ)
  (h: FixedAt f x n) (m: ℕ) (hm: n ≤ m):
    FixedAt f x m := by
  rw [FixedAt_funcIterStream_iff]
  apply FixedAfter1_mono
  rw [FixedAt_funcIterStream_iff] at h
  assumption
  assumption

variable {A B: VType}

-- In the DBSP paper, the while loop program is used to show the Turing-completeness of DBSP.
-- Here we prove that with our new foundation, while programs will always terminate when the
-- fixpoint exists, thus DBSP is still Turing-complete.
namespace WhileLoop
-- Let's assume `c0` is a circuit whose denotation is an arbitrary scalar query and whose ExtFP implies its IntFP.
-- This can be any LiftedScalar circuit, but also include more, which we will see later.
-- `i` is the scalar input, i.e. initial value
variable (c0: Ckt A A 0) (hei: ∀ x n, ExtFP1 c0 x n -> IntFP1 c0 x n) (i: VType_interp A)
-- `f` is the scalar function expressed by `c0`
variable (f: VType_interp A -> VType_interp A) (hf: DenoteLiftedScalar c0 f)

-- The while loop query body (yet to be lifted) between the bracket
def body: Ckt A A 0 :=
  cloop (cadd >>c c0) >>c cD

@[simp]
noncomputable abbrev bodyOutput := denote (body c0) (δ0 i)

include hf in
lemma denote_body:
    bodyOutput c0 i = D (funcIterStream f (f i)) := by
  simp [body, denote]
  apply congr; simp
  rw [hf]; simp [liftO, sprodO]
  funext n; induction n
  case zero =>
    simp [fix_0, funcIterStream, δ0, delay]
  case succ n ih =>
    rw [fix_eq (hstrict := ?_)]
    · simp [δ0, delay, ih, funcIterStream]
      rw [← Function.iterate_succ_apply' f]
      rw [Function.iterate_succ_apply]
    · intro s s' t h; simp
      congr 2
      apply delay_strict
      assumption

include hf in
lemma FixedAt_iff_ZeroAfter (n: ℕ):
    FixedAt f i (n+1) <->
    ZeroAfter (bodyOutput c0 i) (n+1) := by
  rw [FixedAt_funcIterStream_iff]
  rw [denote_body (hf:=hf), ZeroAfter_succ_D_FixedAfter1]
  constructor <;> intro h
  · intro m hm; simp [funcIterStream]
    specialize h (m+1) (by omega)
    simp [funcIterStream] at h; tauto
  · intro m hm; simp [funcIterStream]
    specialize h (m-1) (by omega)
    simp [funcIterStream] at h
    rw [<- h]; rw [<- Function.iterate_succ_apply]
    congr; omega

include hei in
lemma ZeroAfter_body_IntFP1 (n: ℕ)
  (hz: ZeroAfter (bodyOutput c0 i) (n+1)):
    IntFP1 (body c0) (δ0 i) (n+1) := by
  simp [body] at hz ⊢
  have h4 := ZeroAfter_seq_D (hz:=hz)
  have h1 := δ0_ZeroAfter i
  constructor; swap
  · apply D_IntFP1
    simp [denote] at hz ⊢
    tauto
  set add_input := sprod (δ0 i, z⁻¹ (denote (cloop (cadd >>c c0)) (δ0 i)))
  have h2 : FixedAfter1 add_input (n+1) := by
    simp [add_input]
    rw [FixedAfter1_sprod]
    constructor
    · apply FixedAfter1_mono
      apply ZeroAfter_impl_FixedAfter1
      tauto; omega
    · rw [FixedAfter1_delay_succ]
      assumption
  have h3 : FixedAfter1 (denote (ns:=0) cadd add_input) (n+1) := by
    apply FixedAfter1_LiftedScalar
    constructor; assumption
  constructor
  · constructor <;> tauto
  · apply hei
    constructor; tauto
    have := loop_unfold (cadd >>c c0) (δ0 i)
    simp [denote] at this ⊢
    rw [<- this]
    apply FixedAfter1_mono; tauto; omega

include hei in
lemma Terminate_body:
    Terminate (body c0) (δ0 i) := by
  simp [body, Terminate]
  apply Terminate_LiftedScalar; tauto

-- The (streaming) while loop query
def query: Ckt A A 0 :=
  cbracket (c↑ (body c0))

include hf in
theorem denote_query (x: stream (VType_interp A))
  (k n: ℕ) (h: FixedAt f (x k) n):
    denote (query c0) x k = f^[n] (x k) := by
  have h' := h; simp [FixedAt] at h'
  rw [<- h']
  simp [query, denote]
  apply FixedAt_mono at h
  specialize h (n+1) (by omega)
  rw [FixedAt_iff_ZeroAfter (hf:=hf)] at h
  rw [streamElim_zeroAfter (pf:=h)]
  rw [<- integral_sumVals, denote_body (hf:=hf)]
  simp [funcIterStream]

include hf hei

theorem FixedAt_body_IntFP2 (x: stream (VType_interp A))(m n: ℕ)
  (hz: FixedAt f (x m) (n+1)):
    IntFP2 (c↑ (body c0)) (↑↑δ0 x) m (n+1) := by
  rw [FixedAt_iff_ZeroAfter (hf:=hf)] at hz
  simp [IntFP2]
  apply ZeroAfter_body_IntFP1 c0 hei
  simp [denote] at hz ⊢; tauto

theorem IntFP2Vec_body (x: stream (VType_interp A))
  (b: stream ℕ) (hz: FixedAtVec f x b):
    IntFP2Vec (c↑ (body c0)) (↑↑δ0 x) (fun n => max (b n) 1) := by
  simp [IntFP2Vec]; intro i
  rcases h: (b i)
  · simp; apply FixedAt_body_IntFP2 c0 hei f hf
    simp; apply FixedAt_mono
    apply hz; omega
  · simp; apply FixedAt_body_IntFP2 c0 hei f hf
    rw [<- h]; tauto

theorem TerminateRow_query (x: stream (VType_interp A)) m:
    TerminateRow (query c0) x m <->
    ∃ b, FixedAt f (x m) b := by
  constructor
  · intro ht; simp [query, Terminate] at ht
    rcases ht with ⟨_, ⟨b, ⟨_, h⟩⟩⟩
    use (fun n => b n + 1); intro k
    specialize h k; simp [denote] at h
    rw [FixedAt_iff_ZeroAfter (hf:=hf)]
    apply ZeroAfter_ge; tauto; omega
  · rintro ⟨b, h⟩
    simp [query, Terminate]
    constructor
    · intros; apply Terminate_body; tauto
    use (fun n => b n + 1)
    simp [IntFP2Vec, ZeroAfterVec]
    constructor <;> intro i
    · apply FixedAt_body_IntFP2 c0 hei f hf
      apply FixedAt_mono
      apply h; simp
    · simp [denote]
      rw [<- FixedAt_iff_ZeroAfter (hf:=hf)]
      apply FixedAt_mono
      apply h; simp

end WhileLoop

-- Here we show that Datalog-like recursive queries will always terminate
-- when the fixpoint exists.
namespace Datalog
-- Let's assume `c0` is a lifted scalar circuit to express an arbitrary scalar query
variable (c0: Ckt (A ×ᵥ B) B 0) (hei: LiftedScalar c0)
-- `R` is the relational query expressed by `c0`
-- `i` is the scalar input
variable (R: VType_interp (A ×ᵥ B) -> VType_interp B) (hf: DenoteLiftedScalar c0 R) (i: VType_interp A)

-- The recursive query body (yet to be lifted) between the bracket
def body: Ckt A B 0 :=
  cI >>c cloop c0 >>c cD

@[simp]
noncomputable abbrev bodyOutput := denote (body c0) (δ0 i)

-- `f` is the unary function implied by `R`
def f (x: VType_interp B) := R (i, x)

lemma f_unfold (x: VType_interp B):
    f R i x = R (i, x) := by rfl

include hf in
lemma denote_body:
    bodyOutput c0 i = D (funcIterStream (f R i) (f R i 0)) := by
  simp [body, denote]
  apply congr; simp
  rw [hf]; simp [liftO, sprodO]
  funext n; induction n
  case zero =>
    simp [fix_0, funcIterStream, δ0, delay, f]
  case succ n ih =>
    rw [fix_eq (hstrict := ?_)]
    · simp [δ0, delay, ih, funcIterStream]
      rw [<- f_unfold R]
      rw [← Function.iterate_succ_apply' (f R i)]
      rw [Function.iterate_succ_apply]
    · intro s s' t h; simp
      congr 2
      apply delay_strict
      assumption



-- include hei in
-- lemma ZeroAfter_body_IntFP1 (n: ℕ)
--   (hz: ZeroAfter (bodyOutput c0 i) (n+1)):
--     IntFP1 (body c0) (δ0 i) (n+1) := by
--   simp [body] at hz ⊢
--   have h4 := ZeroAfter_seq_D (hz:=hz)
--   have h1 := δ0_ZeroAfter i
--   constructor; swap
--   · apply ZeroAfter_D_IntFP1
--     simp [denote] at hz ⊢
--     tauto
--   set add_input := sprod (δ0 i, z⁻¹ (denote (cloop (cadd >>c c0)) (δ0 i)))
--   have h2 : FixedAfter1 add_input (n+1) := by
--     simp [add_input]
--     rw [FixedAfter1_sprod]
--     constructor
--     · apply FixedAfter1_mono
--       apply ZeroAfter_impl_FixedAfter1
--       tauto; omega
--     · rw [FixedAfter1_delay_succ]
--       assumption
--   have h3 : FixedAfter1 (denote (ns:=0) cadd add_input) (n+1) := by
--     apply FixedAfter1_LiftedScalar
--     constructor; assumption
--   constructor
--   · constructor <;> tauto
--   · apply ExtFP1_LiftedScalar_IntFP1
--     assumption
--     constructor; tauto
--     have := loop_unfold (cadd >>c c0) (δ0 i)
--     simp [denote] at this ⊢
--     rw [<- this]
--     apply FixedAfter1_mono; tauto; omega

-- include hei in
-- lemma Terminate_body:
--     Terminate (body c0) (δ0 i) := by
--   simp [body, Terminate]
--   apply Terminate_LiftedScalar; tauto

-- -- The (streaming) while loop query
-- def query: Ckt A A 0 :=
--   cbracket (c↑ (body c0))

-- include hf in
-- theorem denote_query (x: stream (VType_interp A))
--   (k n: ℕ) (h: FixedAt f (x k) n):
--     denote (query c0) x k = f^[n] (x k) := by
--   have h' := h; simp [FixedAt] at h'
--   rw [<- h']
--   simp [query, denote]
--   apply FixedAt_mono at h
--   specialize h (n+1) (by omega)
--   rw [FixedAt_iff_ZeroAfter (hf:=hf)] at h
--   rw [streamElim_zeroAfter (pf:=h)]
--   rw [<- integral_sumVals, denote_body (hf:=hf)]
--   simp [funcIterStream]

-- include hf hei

-- theorem FixedAt_body_IntFP2 (x: stream (VType_interp A))(m n: ℕ)
--   (hz: FixedAt f (x m) (n+1)):
--     IntFP2 (c↑ (body c0)) (↑↑δ0 x) m (n+1) := by
--   rw [FixedAt_iff_ZeroAfter (hf:=hf)] at hz
--   simp [IntFP2]
--   apply ZeroAfter_body_IntFP1 c0 hei
--   simp [denote] at hz ⊢; tauto

-- theorem IntFP2Vec_body (x: stream (VType_interp A))
--   (b: stream ℕ) (hz: FixedAtVec f x b):
--     IntFP2Vec (c↑ (body c0)) (↑↑δ0 x) (fun n => max (b n) 1) := by
--   simp [IntFP2Vec]; intro i
--   rcases h: (b i)
--   · simp; apply FixedAt_body_IntFP2 c0 hei f hf
--     simp; apply FixedAt_mono
--     apply hz; omega
--   · simp; apply FixedAt_body_IntFP2 c0 hei f hf
--     rw [<- h]; tauto

-- theorem Terminate_query (x: stream (VType_interp A)):
--     Terminate (query c0) x <->
--     ∃ b, FixedAtVec f x b := by
--   constructor
--   · intro ht; simp [query, Terminate] at ht
--     rcases ht with ⟨_, ⟨b, ⟨_, h⟩⟩⟩
--     use (fun n => b n + 1); intro k
--     specialize h k; simp [denote] at h
--     rw [FixedAt_iff_ZeroAfter (hf:=hf)]
--     apply ZeroAfter_ge; tauto; omega
--   · rintro ⟨b, h⟩
--     simp [query, Terminate]
--     constructor
--     · intros; apply Terminate_body; tauto
--     use (fun n => b n + 1)
--     simp [IntFP2Vec, ZeroAfterVec]
--     constructor <;> intro i
--     · apply FixedAt_body_IntFP2 c0 hei f hf
--       apply FixedAt_mono
--       apply h; simp
--     · simp [denote]
--       rw [<- FixedAt_iff_ZeroAfter (hf:=hf)]
--       apply FixedAt_mono
--       apply h; simp

end Datalog

end Expressiveness
