-- We analyze the expressivess of our new foundation here
import DBSP.Termination.Spec
import DBSP.Termination.FPProp
import DBSP.Circuits.LiftedScalar
import DBSP.Logic.Hoare
import DBSP.Logic.HoareT
import DBSP.Practical.Incrementalize
import DBSP.Practical.PushLifting
open CktBasic

-- We first prove some lemmas for LiftedScalar circuits
section Ext2Int
variable {ns: Bool} {A B C: VType}

lemma FixAfter1_LiftedScalar
  (c: Ckt A B ns) (hc: LiftedScalar c)
  x n (hfa: FixAfter1 x n):
    FixAfter1 (denote c x) n := by
  apply LiftedScalar_Denote at hc
  rcases hc with ⟨f, hf⟩
  rw [hf]; apply FixAfter1_liftO; tauto

lemma LiftedScalar_ExtFP1_IntFP1
  (c: Ckt A B ns) (hc: LiftedScalar c)
  x n (he: ExtFP1 c x n):
    IntFP1 c x n := by
  induction hc
  case seq c1 c2 h1 h2 ih1 ih2 =>
    simp [IntFP1]
    have : ExtFP1 c1 x n := by
      simp [ExtFP1] at he ⊢
      constructor; tauto
      apply LiftedScalar_Denote at h1
      rcases h1 with ⟨f, hf⟩
      rw [hf]; apply FixAfter1_liftO; tauto
    have : ExtFP1 c2 (denote c1 x) n := by
      constructor; swap
      · apply he.2
      apply FixAfter1_LiftedScalar; assumption
      apply this.1
    constructor
    · apply ih1; assumption
    · apply ih2; assumption
  case par c1 c2 h1 h2 ih1 ih2 =>
    simp [IntFP1]
    simp [ExtFP1, denote] at he
    rw [FixAfter1_sprodO] at he
    constructor
    · apply ih1; simp [ExtFP1]; tauto
    · apply ih2; simp [ExtFP1]; tauto
  all_goals
    try (simp [IntFP1]; assumption)

@[simp]
theorem Terminate_LiftedScalar
  (c: Ckt A B ns) (hc: LiftedScalar c) x:
    Terminate c x := by
  induction hc <;> try constructor <;> try tauto
  simp [Terminate]; tauto

lemma HoareI1_LiftedScalar {c: Ckt A B ns}
  {v: SOVType ns A} {b: ℕ}
  (hs: LiftedScalar c) (hf: FixAfter1 v b):
    HoareI1 (fun x => x = v) c (fun y => y = denote c v ∧ FixAfter1 y b) b := by
  simp [HoareI1]
  have hf2: FixAfter1 (denote c v) b := by
    apply FixAfter1_LiftedScalar <;> tauto
  simp [hf2]
  apply LiftedScalar_ExtFP1_IntFP1; tauto
  simp [ExtFP1]; tauto

end Ext2Int

-- Some lemmas on function iteration.

-- The stream generated by function iteration of `f` on `x`
-- i.e. `x, f(x), f(f(x)), f(f(f(x))), ...`
def funcIterStream {A: Type} (f: A -> A) (x: A): stream A :=
  fun n => f^[n] x

@[simp]
lemma funcIterStream_apply {A: Type} (f: A -> A) (x: A) (n: ℕ):
    funcIterStream f x n = f^[n] x := by rfl

lemma funcIterStream_0_delay {A: Type} (f: A -> A) [Zero A]:
    funcIterStream f 0 = z⁻¹ (funcIterStream f (f 0)) := by
  funext n; simp [funcIterStream]
  rcases n with _ | n <;> simp

lemma f_apply_funcIterStream {A: Type} (f: A -> A) (x: A):
     ↑↑f (funcIterStream f x) = funcIterStream f (f x) := by
  funext i; simp
  rw [<- Function.iterate_succ_apply, <- Function.iterate_succ_apply' f]

def FixedAt {A: Type} (f: A -> A) (x: A) (n: ℕ): Prop :=
    f^[n+1] x = f^[n] x

def FixedAtVec {A: Type} (f: A -> A) (x: stream A) (b: stream ℕ): Prop :=
  ∀ i, FixedAt f (x i) (b i)

lemma FixedAt_funcIterStream_iff {A: Type} (f: A -> A) (x: A) (n: ℕ):
    FixedAt f x n <-> FixAfter1 (funcIterStream f x) n := by
  unfold FixedAt
  constructor
  · intro h; rw [add_comm] at h
    rw [Function.iterate_add_apply] at h; simp at h
    intro m hm; simp [funcIterStream]
    apply Function.iterate_fixed at h
    specialize h (m-n)
    rw [<- Function.iterate_add_apply] at h
    rw [<- h]; congr; omega
  · intro h
    apply h; omega

lemma FixedAt_mono {A: Type} (f: A -> A) (x: A) (n: ℕ)
  (h: FixedAt f x n) (m: ℕ) (hm: n ≤ m):
    FixedAt f x m := by
  rw [FixedAt_funcIterStream_iff]
  apply FixAfter1_mono
  rw [FixedAt_funcIterStream_iff] at h
  assumption
  assumption

-- In the DBSP paper, the while loop program is used to show the Turing-completeness of DBSP.
-- Here we prove that with our new foundation, while programs will always terminate when the
-- fixpoint exists, thus DBSP is still Turing-complete.
namespace WhileLoop
variable {A: VType}
-- Let's assume `c0` is a circuit whose denotation is an arbitrary scalar query, whose ExtFP implies its IntFP and terminates on specific inputs.
-- An example of such circuit is a LiftedScalar circuit.
variable (c0: Ckt A A 0) (hei: ∀ x n, ExtFP1 c0 x n -> IntFP1 c0 x n)
-- `iv` is the scalar input, i.e. initial value
-- `f` is the scalar function expressed by `c0`
variable (f: VType_interp A -> VType_interp A) (iv: VType_interp A) (hf: DenoteLiftedScalar c0 f)
  (ht: Terminate c0 (funcIterStream f iv))

-- The while loop query body (yet to be lifted) between the bracket
def body: Ckt A A 0 :=
  cloop (cadd >>c c0) >>c cD

include hf in
lemma loop_output:
  Hoare
    (fun x i => x i = δ0 iv i)
    (cloop (cadd >>c c0))
    (fun y i => y i = funcIterStream f (f iv) i) := by
  apply Hoare_loop
  simp [Hoare, TrueUntil, liftO, denote]
  intro x n h m hm
  rw [hf]; simp [liftO]
  specialize h m hm
  rcases m with _ | m
  · simp at h
    aesop
  · simp [drop] at h
    rw [Function.iterate_succ_apply']
    rw [add_comm 1 m] at h
    aesop

include hf ht in
lemma loop_HoareT:
  HoareT
    (fun x => x = δ0 iv)
    (cloop (cadd >>c c0))
    (fun y => y = funcIterStream f (f iv)) := by
  rw [fun_stream_eq_forall, fun_stream_eq_forall]
  apply HoareT_loop (by apply loop_output; tauto)
  intro x y hx hy
  rw [<- funext_iff] at hx hy
  simp [HoareT, sprodO, Terminate, denote]
  have : x + z⁻¹ y = funcIterStream f iv := by
    rw [hx, hy]; funext i
    rcases i with _ | i <;> simp
  rw [this]
  tauto

abbrev bodyOutput :=
  D (funcIterStream f (f iv))

lemma FixedAt_iff_ZeroAfter (n: ℕ):
    FixedAt f iv (n+1) <->
    ZeroAfter (bodyOutput f iv) (n+1) := by
  rw [FixedAt_funcIterStream_iff]
  rw [bodyOutput, ZeroAfter_succ_D_FixAfter1]
  constructor <;> intro h
  · intro m hm; simp [funcIterStream]
    specialize h (m+1) (by omega)
    simp [funcIterStream] at h; tauto
  · intro m hm; simp [funcIterStream]
    specialize h (m-1) (by omega)
    simp [funcIterStream] at h
    rw [<- h]; rw [<- Function.iterate_succ_apply]
    congr; omega

include hf ht in
lemma body_HoareT:
  HoareT
    (fun x => x = δ0 iv)
    (body c0)
    (fun y => y = bodyOutput f iv) := by
  unfold body; apply HoareT_seq
  apply loop_HoareT <;> tauto
  simp [HoareT]

include hf ht hei in
lemma body_HoareI1 {n: ℕ}
  (hfa: FixedAt f iv (n+1)):
    HoareI1
      (fun x => x = δ0 iv)
      (body c0)
      (fun _ => True) (n+1) := by
  unfold body
  rw [FixedAt_iff_ZeroAfter] at hfa
  rw [bodyOutput, ZeroAfter_succ_D_FixAfter1] at hfa
  apply HoareI1_seq
  apply HoareI1_loop (by apply loop_HoareT <;> tauto)
  · intro x y hx hy; simp
    apply HoareI1_seq
    apply HoareI1_LiftedScalar (by constructor)
    · rw [FixAfter1_sprod]
      constructor
      · apply FixAfter1_mono
        apply ZeroAfter_impl_FixAfter1
        rw [hx]; apply δ0_ZeroAfter; omega
      · rw [FixAfter1_delay_succ]
        rw [hy]; tauto
    simp [denote]
    have : x + z⁻¹ y = funcIterStream f iv := by
      rw [hx, hy]; funext i
      rcases i with _ | i <;> simp
    rw [this]
    simp [HoareI1]
    intro hf'; apply hei
    simp [hf', ExtFP1]
    rw [hf]; simp
    rw [f_apply_funcIterStream]
    apply FixAfter1_mono <;> tauto
  apply HoareI1_conseq_post (hq:= by tauto)
  apply HoareI1_D; tauto

-- The (streaming) while loop query
def query: Ckt A A 0 :=
  cbracket (c↑ (body c0))

variable {b: stream ℕ} {is: stream (VType_interp A)}
  (hfa: FixedAtVec f is b) (htv: ∀ i, Terminate c0 (funcIterStream f (is i)))

theorem query_ExtFP1_IntFP1 {n: ℕ}
  (he: ExtFP1 (query c0) is n):
    IntFP1 (query c0) is n := by
  simp [query, IntFP1]
  rw [lifted_Ckt_ExtFP1 (hc:=by simp)]
  rcases he with ⟨hf, _⟩
  intro m hm
  specialize hf m hm
  funext k; simp
  rw [hf]

include hf htv hei hfa

theorem lifted_body_HoareI2:
  HoareI2
    (fun x => x = ↑↑δ0 is)
    (c↑ (body c0))
    (fun _ => True)
    (fun i => b i + 1) := by
  rw [fun_stream_eq_forall]; simp
  apply HoareI2_conseq_post
  apply HoareI2_lifting (P := fun j x => x = δ0 (is j))
    (Q := fun _ _ => True)
  intro j; apply body_HoareI1
  all_goals try tauto
  apply FixedAt_mono; tauto; omega

theorem query_HoareT:
  HoareT
    (fun x => x = is)
    (query c0)
    (fun y => y = fun i => f^[b i] (is i)) := by
  unfold query; apply HoareT_conseq_post
  apply HoareT_bracket (fun i => b i + 1)
  · simp; rw [fun_stream_eq_forall]; simp
    apply HoareT_lifting (P := fun j x => x = δ0 (is j))
      (Q := fun j y => y = bodyOutput f (is j))
    intro j; apply body_HoareT <;> tauto
  · simp; apply lifted_body_HoareI2 <;> tauto
  · intro z; rw [<- funext_iff]
    intro hz; subst hz
    intro j; simp
    rw [<- FixedAt_iff_ZeroAfter]
    apply FixedAt_mono; tauto; omega
  simp; intro x y
  rw [<- funext_iff]
  intro hy; subst hy; simp
  intro h; funext i; specialize h i
  simp [bodyOutput, D] at h
  rw [<- Function.iterate_succ_apply, <- Function.iterate_succ_apply] at h
  rw [h]; specialize hfa i
  rw [FixedAt_funcIterStream_iff] at hfa
  apply hfa; omega

theorem query_Terminate:
    Terminate (query c0) is := by
  apply And.left
  apply query_HoareT <;> tauto

end WhileLoop

-- Here we show that Datalog-like recursive queries will always terminate
-- when the fixpoint exists.
namespace Datalog
variable {A B: VType}
-- Let's assume `c0` is a circuit whose denotation is an arbitrary scalar query, whose ExtFP implies its IntFP and terminates on specific inputs.
-- An example of such circuit is a LiftedScalar circuit.
variable (c0: Ckt (A ×ᵥ B) B 0) (hei: ∀ x n, ExtFP1 c0 x n -> IntFP1 c0 x n)
-- `R` is the relational query expressed by `c0`
-- `iv` is the scalar input
variable (R: VType_interp (A ×ᵥ B) -> VType_interp B) (hf: DenoteLiftedScalar c0 R) (iv: VType_interp A)

-- `f` is the unary function implied by `R`
def f (x: VType_interp B) := R (iv, x)

lemma f_unfold (x: VType_interp B):
    f R iv x = R (iv, x) := by rfl

abbrev c0_input := sprod ((fun _ => iv), (funcIterStream (f R iv) 0))

variable (ht: Terminate c0 (c0_input R iv))

-- The recursive query body (yet to be lifted) between the bracket
def body: Ckt A B 0 :=
  cΔ (cloop c0)

include hf in
lemma loop_output:
  Hoare
    (fun x i => x i = iv)
    (cloop c0)
    (fun y i => y i = funcIterStream (f R iv) (f R iv 0) i) := by
  apply Hoare_loop
  simp [Hoare, TrueUntil, denote]
  intro x n h m hm
  rw [hf]; simp
  specialize h m hm
  rcases m with _ | m
  · simp [f] at h ⊢
    rw [<- h.1, <- h.2]
  · simp [f, drop] at h
    rw [Function.iterate_succ_apply']
    rw [add_comm 1 m] at h
    simp [f]; rw [<- h.2, <- h.1]

include hf ht in
lemma loop_HoareT:
  HoareT
    (fun x => x = fun _ => iv)
    (cloop c0)
    (fun y => y = funcIterStream (f R iv) (f R iv 0)) := by
  rw [fun_stream_eq_forall, fun_stream_eq_forall]
  apply HoareT_loop (by apply loop_output; tauto)
  intro x y hx hy
  rw [<- funext_iff] at hx hy
  simp [HoareT, sprodO, Terminate, denote]
  have : z⁻¹ y = funcIterStream (f R iv) 0 := by
    rw [hy]; funext i
    rcases i with _ | i <;> simp
  rw [this, hx]
  tauto

abbrev bodyOutput :=
  D (funcIterStream (f R iv) (f R iv 0))

lemma FixedAt_iff_ZeroAfter (n: ℕ):
    FixedAt (f R iv) 0 (n+1) <->
    ZeroAfter (bodyOutput R iv) (n+1) := by
  rw [FixedAt_funcIterStream_iff]
  rw [bodyOutput, ZeroAfter_succ_D_FixAfter1]
  constructor <;> intro h
  · intro m hm; simp [funcIterStream]
    specialize h (m+1) (by omega)
    simp [funcIterStream] at h; tauto
  · intro m hm; simp [funcIterStream]
    specialize h (m-1) (by omega)
    simp [funcIterStream] at h
    rw [<- h]; rw [<- Function.iterate_succ_apply]
    congr; omega

-- Theorem: FirstZero is a valid fixpoint detection strategy for the Datalog body circuit.
-- i.e. the body output is zero at step n if and only if it is ZeroAfter n.
theorem FirstZero_valid {n: ℕ}:
    ZeroAfter (bodyOutput R iv) n <-> bodyOutput R iv n = 0 := by
  constructor
  · tauto
  intro hz
  have hfix: FixedAt (f R iv) 0 n := by
    simp [FixedAt, bodyOutput, D, delay] at hz ⊢
    rcases n with _ | n
    · simpa using hz
    · simp at hz; rw [sub_eq_zero] at hz; tauto
  rcases n with _ | n
  · -- n = 0: FixedAt f 0 0 means f 0 = 0, so all iterates are 0
    simp [FixedAt] at hfix
    have hall : ∀ k, (f R iv)^[k] 0 = 0 := by
      intro k; induction k with
      | zero => simp
      | succ k ih => rw [Function.iterate_succ_apply']; rw [ih]; exact hfix
    intro m _; simp [bodyOutput, D, delay]
    rcases m with _ | m
    · simpa using hfix
    · simp; rw [sub_eq_zero]; rw [show f R iv 0 = 0 from hfix]; simp [hall]
      rw [<- Function.iterate_succ_apply]; simp [hall]
  · rw [<- FixedAt_iff_ZeroAfter]; tauto

include hf ht hei in
lemma loop_HoareI1 {n: ℕ}
  (hfa: FixedAt (f R iv) 0 (n+1)):
    HoareI1
      (fun x => x = fun _ => iv)
      (cloop c0)
      (fun y => y = funcIterStream (f R iv) (f R iv 0)) (n+1) := by
  rw [FixedAt_iff_ZeroAfter] at hfa
  rw [bodyOutput, ZeroAfter_succ_D_FixAfter1] at hfa
  apply HoareI1_loop (by apply loop_HoareT <;> tauto)
  · intro x y hx hy; simp
    simp [HoareI1]; apply hei
    simp [ExtFP1]
    have : denote c0 (sprod (x, z⁻¹ y)) = funcIterStream (f R iv) (f R iv 0) := by
      rw [hf, hx, hy]; simp
      funext k; simp
      rw [<- f_unfold R]
      rcases k with _ | k
      · simp
      · simp; set g := (f R iv)
        rw [<- Function.iterate_succ_apply, <- Function.iterate_succ_apply]
        rw [<- Function.iterate_succ_apply, <- Function.iterate_succ_apply' g]
    rw [this, hx, hy]; constructor
    · rw [FixAfter1_sprod]; simp
      rw [FixAfter1_delay_succ]; tauto
    · apply FixAfter1_mono; tauto; omega

include hf ht in
lemma body_HoareT:
  HoareT
    (fun x => x = δ0 iv)
    (body c0)
    (fun y => y = bodyOutput R iv) := by
  unfold body; apply HoareT_seq
  apply HoareT_seq; swap
  apply loop_HoareT <;> tauto
  simp [HoareT, integral_delta]
  simp [HoareT, bodyOutput]

include hf ht hei in
lemma body_HoareI1 {n: ℕ}
  (hfa: FixedAt (f R iv) 0 (n+1)):
    HoareI1
      (fun x => x = δ0 iv)
      (body c0)
      (fun _ => True) (n+1) := by
  unfold body
  rw [FixedAt_iff_ZeroAfter] at hfa
  rw [bodyOutput, ZeroAfter_succ_D_FixAfter1] at hfa
  apply HoareI1_seq; apply HoareI1_seq
  apply HoareI1_mono
  apply HoareI1_I; apply δ0_ZeroAfter; omega
  rw [integral_delta]
  apply loop_HoareI1 <;> tauto
  apply HoareI1_conseq_post (hq:= by tauto)
  apply HoareI1_D; tauto

-- The (streaming) Datalog recursive query
def query: Ckt A B 0 :=
  cbracket (c↑ (body c0))

variable {b: stream ℕ} {is: stream (VType_interp A)}
  (hfa: ∀ j, FixedAt (f R (is j)) 0 (b j)) (htv: ∀ j, Terminate c0 (c0_input R (is j)))

include hf htv hei hfa in
theorem lifted_body_HoareI2:
  HoareI2
    (fun x => x = ↑↑δ0 is)
    (c↑ (body c0))
    (fun _ => True)
    (fun i => b i + 1) := by
  rw [fun_stream_eq_forall]; simp
  apply HoareI2_conseq_post
  apply HoareI2_lifting (P := fun j x => x = δ0 (is j))
    (Q := fun _ _ => True)
  intro j; apply body_HoareI1
  all_goals try tauto
  apply FixedAt_mono; tauto; omega

include hf htv hei hfa in
theorem query_HoareT:
  HoareT
    (fun x => x = is)
    (query c0)
    (fun y => y = fun i => (f R (is i))^[b i] 0) := by
  unfold query; apply HoareT_conseq_post
  apply HoareT_bracket (fun i => b i + 1)
  · simp; rw [fun_stream_eq_forall]; simp
    apply HoareT_lifting (P := fun j x => x = δ0 (is j))
      (Q := fun j y => y = bodyOutput R (is j))
    intro j; apply body_HoareT <;> tauto
  · simp; apply lifted_body_HoareI2 <;> tauto
  · intro z; rw [<- funext_iff]
    intro hz; subst hz
    intro j; simp
    rw [<- FixedAt_iff_ZeroAfter]
    apply FixedAt_mono; tauto; omega
  simp; intro x y
  rw [<- funext_iff]
  intro hy; subst hy; simp
  intro h; funext i; specialize h i
  simp [bodyOutput, D] at h
  rw [<- Function.iterate_succ_apply, <- Function.iterate_succ_apply] at h
  rw [h]; specialize hfa i
  rw [FixedAt_funcIterStream_iff] at hfa
  apply hfa; omega

include hf htv hei hfa in
theorem query_Terminate:
    Terminate (query c0) is := by
  apply And.left
  apply query_HoareT <;> tauto

theorem query_ExtFP1_IntFP1 {n: ℕ}
  (he: ExtFP1 (query c0) is n):
    IntFP1 (query c0) is n := by
  simp [query, IntFP1]
  rw [lifted_Ckt_ExtFP1 (hc:=by simp)]
  rcases he with ⟨hf, _⟩
  intro m hm
  specialize hf m hm
  funext k; simp
  rw [hf]

-- theorems about the incremental optimized query
variable [hic: IncCkt c0]

include hf ht in
lemma opt_body_HoareT:
  HoareT
    (fun x => x = δ0 iv)
    (cloop (incOpt c0))
    (fun y => y = bodyOutput R iv) := by
  apply HoareT_Refine (h1:= by apply body_HoareT <;> tauto)
  apply incOpt_Refine

include hf ht hei in
lemma opt_body_HoareI1 {n: ℕ}
  (hfa: FixedAt (f R iv) 0 (n+1)):
    HoareI1
      (fun x => x = δ0 iv)
      (cloop (incOpt c0))
      (fun _ => True) (n+2) := by
  rw [delta_D_const]
  apply HoareI1_Preserve1
  case ht => apply loop_HoareT <;> tauto
  case h1 => apply loop_HoareI1 <;> tauto
  apply incOpt_Preserve1

include hf htv in
lemma lifted_opt_body_HoareT:
    HoareT
      (fun x => x = ↑↑δ0 is)
      (cloop2 (pushLifting (incOpt c0)))
      (fun y => y =  ↑↑(bodyOutput R) is) := by
  rw [<- pushLifting]
  rw [fun_stream_eq_forall]; simp
  apply HoareT_conseq_post
  apply HoareT_pushLifting (P := fun j x => x = δ0 (is j))
  intro j; apply opt_body_HoareT <;> tauto
  intros; funext _; tauto

-- Let's assume `pushLifting (incOpt c0)` simplifies to `c1` which is incrementalizable
variable (c1: Ckt (A×ᵥB) B 1) (hc1: pushLifting (incOpt c0) = c1) [h1ic: IncCkt c1]
include hc1

include hf htv in
theorem opt_lifted_body_HoareT :
    HoareT
      (fun x => x = ↑↑δ0 (D is))
      (cloop2 (incOpt c1))
      (fun y => y = D (↑↑(bodyOutput R) is)) := by
  apply HoareT_Refine
  apply incOpt_Refine (c:= cloop2 c1)
  rw [<- D_lifting_delta_comm]
  apply HoareT_Δ
  subst hc1
  apply lifted_opt_body_HoareT <;> tauto

include hf htv hei hfa in
theorem opt_lifted_body_HoareI2:
    HoareI2
      (fun x => x = ↑↑δ0 (D is))
      (cloop2 (incOpt c1))
      (fun _ => True)
      (fun i => max (b i + 2) (z⁻¹ (fun j => b j + 2) i)) := by
  subst hc1
  rw [<- D_lifting_delta_comm]
  apply HoareI2_bound_mono
  case hi =>
    apply HoareI2_Preserve2 (c1:= cloop2 (pushLifting (incOpt c0)))
    case h => apply incOpt_Preserve2
    case ht => apply lifted_opt_body_HoareT <;> tauto
    case h1 =>
      rw [<- pushLifting]
      rw [fun_stream_eq_forall]; simp
      apply HoareI2_pushLifting (P := fun j x => x = δ0 (is j))
      intro j; apply opt_body_HoareI1 <;> try tauto
      apply FixedAt_mono; tauto; tauto
  simp

abbrev opt_query :=
  cbracket (cloop2 (incOpt c1))

include hf htv hei hfa in
theorem opt_query_HoareT:
    HoareT
      (fun x => x = D is)
      (opt_query c1)
      (fun y => y = D (fun i => (f R (is i))^[b i] 0)) := by
  subst hc1
  apply HoareT_conseq_post
  apply HoareT_bracket
  case hi =>
    intro y _; subst y
    apply opt_lifted_body_HoareI2 (hc1:=rfl) <;> tauto
  case ht =>
    intro y _; subst y
    apply opt_lifted_body_HoareT (hc1:=rfl) <;> tauto
  case hb =>
    intro z hz; subst hz
    intro j; simp
    apply ZeroAfterVec_D
    intro k; simp
    rw [<- FixedAt_iff_ZeroAfter]
    apply FixedAt_mono; tauto; omega
  simp; intro x h
  funext i; specialize h i
  rw [h]; unfold D; simp
  rw [linear_sub integral_linear]
  have hfa: ∀ (j : ℕ), FixAfter1 (funcIterStream (f R (is j)) 0) (b j) := by
    intro j; specialize hfa j
    rw [FixedAt_funcIterStream_iff] at hfa; tauto
  rcases i with _ | i
  · simp
    repeat rw [<- Function.iterate_succ_apply]
    apply hfa; omega
  · simp
    apply congr
    apply congr; rfl
    all_goals
    repeat rw [<- Function.iterate_succ_apply]
    apply hfa; omega

end Datalog
